# This is a basic workflow to help you get started with Actions

name: Prepare Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.8.8
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64 # optional

      - name: Prepare Git (fetch, etc.)
        run: |
          git config --global user.email "gh-actions-penguinencounter-wip@example.com"
          git config --global user.name "PenguinEncounter's Repository Management Github Actions Robot v1"
          git fetch
      
      # Runs a set of commands using the runners shell
      - name: Build and Publish
        run: |
          pushd $GITHUB_WORKSPACE
          python3 lightbuild.py
          popd
            
